//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCustomers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked_Rooms
    {
        public Nullable<int> Rooms_ID { get; set; }
        public Nullable<int> Clients_ID { get; set; }
        public System.DateTime Begins { get; set; }
        public System.DateTime Ends { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
