//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_California___Data_manipulation_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked_Rooms
    {
        public int Reservation_ID { get; set; }
        public Nullable<int> Rooms_ID { get; set; }
        public Nullable<int> Clients_ID { get; set; }
        public System.DateTime Begins { get; set; }
        public System.DateTime Ends { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
