//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_California___Data_manipulation_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Type
    {
        public Nullable<int> Task_ID { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public string Type { get; set; }
    
        public virtual Post_Type Post_Type { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
