//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_California___Data_manipulation_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Task_ID { get; set; }
        public Nullable<int> ID_ROOM { get; set; }
        public string Task_Type { get; set; }
        public string Status { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
